version: "3.7"
services:
  app:
    build:
      args:
        user: carmen
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pfguned
    container_name: pfguned-app
    restart: unless-stopped
    environment:
     - COMPOSER_MEMORY_LIMIT=-1
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pfguned

  db:
    image: mysql:5.7
    container_name: pfguned-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - pfguned
    ports:
    - "53306:3306"

  nginx:
    image: nginx:alpine
    container_name: pfguned-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pfguned

networks:
  pfguned:
    driver: bridge
